title: Guy de Faye
email: guydefayejersey@gmail.com
description: >
  Guy de Faye is standing for Senator in the Jersey General
  Elections. Vote for Guy on Wednesday 15 October 2014.
baseurl: ""
url: "http://guydefaye.com"
markdown: kramdown
google_analytics_tracking_id: 'UA-55231934-1'
